from app import app
from app.forms import PodcastSearchForm
from flask import Flask, render_template, request, redirect, url_for
import json


@app.route('/', methods=['GET', 'POST'])
@app.route('/index')

def index():
    podcasts = [{
    "title": "Folge 106: \"Lebenszufriedenheit nicht gegen mehr Geld eintauschen!\" - Hörerinterview mit Stefan",
    "itunes_title": "Folge 106: \"Lebenszufriedenheit nicht gegen mehr Geld eintauschen!\" - Hörerinterview mit Stefan",
    "episode": "106",
    "date": "Wed, 17 Oct 2018 04:47:29 +0000",
    "link": "https://finanzrocker.podigee.io/106-folge-106-lebenszufriedenheit-nicht-gegen-mehr-geld-eintauschen-horerinterview-mit-stefan",
    "author": "Daniel Korth - Finanz-Blogger, Podcaster und Co-Host von \"Der Finanzwesir rockt\"",
    "description": "In der heutigen Podcast-Folge spreche ich mit meinem Hörer Stefan über seine ungewöhnliche Karriere vom Banker zum Heavy-Metal-Label, Disruption in der Musikindustrie und warum Geld nicht immer für Lebenszufriedenheit sorgt. Aber auch die Themen Aktien und Geldanlage allgemein kommen nicht zu kurz.Vor einigen Monate meldete sich Stefan mit einer sehr langen E-Mail bei mir. Ihm war in meinen Bewertungen aufgefallen, dass einige sich einen größeren Rock-Faktor im Finanzrocker-Podcast wünschen. Da er in der Musikindustrie arbeitet, Stammhörer meines Podcasts ist und auch aktiv sein Geld anlegt, bot er an, dass wir in einem gemeinsamen Gespräch mehr Rockmusik reinbringen können. Da seine Vita komplett anders ist als bei den meisten anderen, war mein Interesse geweckt.Aber keine Angst: Das Thema Musik spielt dennoch keine so übergeordnete Rolle. Vielmehr sprechen wir über Stefans etwas andere \"Karriere\" vom Banker zum Labelmanager bei einem Nischenlabel, seine Geldanlage in Einzelaktien und P2P-Kredite, Gespräche über Geld und die CD-Sammlung als Sachwert. Gerade zum ende hin unterscheidet sich das Gespräch deutlich von anderen Hörerinterviews.Und die Kernbotschaft ganz am Ende lautet: Mach das, was dir Spaß macht und Lebenszufriedenheit bringt und denk nicht immer nur ans Geld! Sonst bereust du es irgendwann. Eine wichtige Aussage, wie ich finde.ShownotesProphecy ProductionsBondora Go & Grow: Meine Erfahrungen mit der PlattformDiscogs - Sammlung einpflegen und Wert bestimmenSachwerte als Geldanlage Teil 1: CDs, Edelmetalle und MünzenSachwerte als Geldanlage Teil 2: Von Teppichen und T-Shirts\"Lieber ETF statt Handtasche\" - Hörerinterview mit Philine\"In Deutschland geht es uns doch gut\" - Hörerinterview mit Garvin\"Geerbt - und nun?\" - Hörerinterview mit Marcus\"Mehrere Einkommensströme generieren\" - Hörerinterview mit Michaela„Keine Angst vor Karten, Konten und Apps!“ – Hörerinterview mit Daniel\"Mit der Walt-Disney-Dividende ins Kino!\" - Leserinterview mit Tobias\"90 % vom Vermögen mit Aktien verloren\" - Leserinterview mit Roman WandagJubiläumsfolge: Hörerinterview mit AliciaPräsentiert von BlinkistDiese Folge wird Dir präsentiert von Blinkist, der App für Menschen, die mehr wissen möchten. Blinkist ist eine App, mit der du dir die Kernaussagen aus über 2.500 Büchern in nur 15 Minuten durchlesen oder anhören kannst.Thematisch werden dort alle Themen rund um den Finanzrocker-Podcast abgedeckt wie Finanzen, Persönliche Entwicklung. Im Moment gibt es eine Aktion exklusiv für Hörer meines Podcast erhältst Du 25% Rabatt auf das Jahresabo Blinkist Premium. Es gibt ein Probeabo mit dem ihr kostenlos alles testen und euch in Ruhe anschauen könnt.Hol‘ Dir 25 % Rabatt auf das Premium-Jahresabo hier. ",
    "summary": "In der heutigen Podcast-Folge spreche ich mit meinem Hörer Stefan über seine ungewöhnliche Karriere vom Banker zum Heavy-Metal-Label, Disruption in der Musikindustrie und warum Geld nicht immer für Lebenszufriedenheit sorgt. Aber auch die Themen Aktien und Geldanlage allgemein kommen nicht zu kurz.Vor einigen Monate meldete sich Stefan mit einer sehr langen E-Mail bei mir. Ihm war in meinen Bewertungen aufgefallen, dass einige sich einen größeren Rock-Faktor im Finanzrocker-Podcast wünschen. Da er in der Musikindustrie arbeitet, Stammhörer meines Podcasts ist und auch aktiv sein Geld anlegt, bot er an, dass wir in einem gemeinsamen Gespräch mehr Rockmusik reinbringen können. Da seine Vita komplett anders ist als bei den meisten anderen, war mein Interesse geweckt.Aber keine Angst: Das Thema Musik spielt dennoch keine so übergeordnete Rolle. Vielmehr sprechen wir über Stefans etwas andere \"Karriere\" vom Banker zum Labelmanager bei einem Nischenlabel, seine Geldanlage in Einzelaktien und P2P-Kredite, Gespräche über Geld und die CD-Sammlung als Sachwert. Gerade zum ende hin unterscheidet sich das Gespräch deutlich von anderen Hörerinterviews.Und die Kernbotschaft ganz am Ende lautet: Mach das, was dir Spaß macht und Lebenszufriedenheit bringt und denk nicht immer nur ans Geld! Sonst bereust du es irgendwann. Eine wichtige Aussage, wie ich finde.ShownotesProphecy ProductionsBondora Go & Grow: Meine Erfahrungen mit der PlattformDiscogs - Sammlung einpflegen und Wert bestimmenSachwerte als Geldanlage Teil 1: CDs, Edelmetalle und MünzenSachwerte als Geldanlage Teil 2: Von Teppichen und T-Shirts\"Lieber ETF statt Handtasche\" - Hörerinterview mit Philine\"In Deutschland geht es uns doch gut\" - Hörerinterview mit Garvin\"Geerbt - und nun?\" - Hörerinterview mit Marcus\"Mehrere Einkommensströme generieren\" - Hörerinterview mit Michaela„Keine Angst vor Karten, Konten und Apps!“ – Hörerinterview mit Daniel\"Mit der Walt-Disney-Dividende ins Kino!\" - Leserinterview mit Tobias\"90 % vom Vermögen mit Aktien verloren\" - Leserinterview mit Roman WandagJubiläumsfolge: Hörerinterview mit AliciaPräsentiert von BlinkistDiese Folge wird Dir präsentiert von Blinkist, der App für Menschen, die mehr wissen möchten. Blinkist ist eine App, mit der du dir die Kernaussagen aus über 2.500 Büchern in nur 15 Minuten durchlesen oder anhören kannst.Thematisch werden dort alle Themen rund um den Finanzrocker-Podcast abgedeckt wie Finanzen, Persönliche Entwicklung. Im Moment gibt es eine Aktion exklusiv für Hörer meines Podcast erhältst Du 25% Rabatt auf das Jahresabo Blinkist Premium. Es gibt ein Probeabo mit dem ihr kostenlos alles testen und euch in Ruhe anschauen könnt.Hol‘ Dir 25 % Rabatt auf das Premium-Jahresabo hier. "
}, {
    "title": "Folge 105: \"Provisionsverkauf ist korrumpierend!\" - Interview mit Anette Weiß von geld.wert Finanzbildung",
    "itunes_title": "Folge 105: \"Provisionsverkauf ist korrumpierend!\" - Interview mit Anette Weiß von geld.wert Finanzbildung",
    "episode": "105",
    "date": "Wed, 03 Oct 2018 07:17:49 +0000",
    "link": "https://finanzrocker.podigee.io/105-folge-105-provisionsverkauf-ist-korrumpierend-interview-mit-anette-weiss-von-geld-wert-finanzbildung",
    "author": "Daniel Korth - Finanz-Blogger, Podcaster und Co-Host von \"Der Finanzwesir rockt\"",
    "description": "In Folge 105 habe ich Anette Weiß zu Gast. Sie vermittelt Finanzbildung auf etwas andere Art und Weise und achtet darauf, dass sie keinen Provisionsverkauf macht. Über das Warum und einiges mehr sprechen wir in der interessanten Podcast-Folge.Bisher habe ich Anette noch nie persönlich kennengelernt. Erst durch ein Bloginterview meiner Kollegin Katharina mit Anette für den oncampus-Blog hatte ich die Idee, mit ihr ein ausführliches Interview zu führen. Nachdem wir unseren Gesprächstermin schon im Mai ausmachten, war es dann Ende August endlich so weit.In dem Interview kam sehr gut rüber, dass Anette komplett anders vorgeht als ihre Kollegen aus der Honorarberatung. Deswegen vermittelt sie in erster Linie auch keine Produkte, sondern Finanzbildung, die ihre Kunden befähigt, eigenständig anzulegen. Ausführlich erklärt sie im Gespräch, wieso sie es so macht, worauf man bei der Altersvorsorge achten sollte und warum sie Provisionsverkauf nicht mag. Es ist ein wirklich interessantes Interview geworden.Einen Auszug findest du im Blogartikel.ShownotesZu Anettes WebseiteWann du riestern solltestKannst du doch alles im Internet lesen!Wie man eine Rentenversicherung bewertetMehr über den Geldlehrer e.V. erfahrenPräsentiert von BlinkistDiese Folge wird Dir präsentiert von Blinkist, der App für Menschen, die mehr wissen möchten. Blinkist ist eine App, mit der du dir die Kernaussagen aus über 2.500 Büchern in nur 15 Minuten durchlesen oder anhören kannst.Thematisch werden dort alle Themen rund um den Finanzrocker-Podcast abgedeckt wie Finanzen, Persönliche Entwicklung. Im Moment gibt es eine Aktion exklusiv für Hörer meines Podcast erhältst Du 25% Rabatt auf das Jahresabo Blinkist Premium. Es gibt ein Probeabo mit dem ihr kostenlos alles testen und euch in Ruhe anschauen könnt.Hol‘ Dir 25 % Rabatt auf das Premium-Jahresabo hier.",
    "summary": "In Folge 105 habe ich Anette Weiß zu Gast. Sie vermittelt Finanzbildung auf etwas andere Art und Weise und achtet darauf, dass sie keinen Provisionsverkauf macht. Über das Warum und einiges mehr sprechen wir in der interessanten Podcast-Folge.Bisher habe ich Anette noch nie persönlich kennengelernt. Erst durch ein Bloginterview meiner Kollegin Katharina mit Anette für den oncampus-Blog hatte ich die Idee, mit ihr ein ausführliches Interview zu führen. Nachdem wir unseren Gesprächstermin schon im Mai ausmachten, war es dann Ende August endlich so weit.In dem Interview kam sehr gut rüber, dass Anette komplett anders vorgeht als ihre Kollegen aus der Honorarberatung. Deswegen vermittelt sie in erster Linie auch keine Produkte, sondern Finanzbildung, die ihre Kunden befähigt, eigenständig anzulegen. Ausführlich erklärt sie im Gespräch, wieso sie es so macht, worauf man bei der Altersvorsorge achten sollte und warum sie Provisionsverkauf nicht mag. Es ist ein wirklich interessantes Interview geworden.Einen Auszug findest du im Blogartikel.ShownotesZu Anettes WebseiteWann du riestern solltestKannst du doch alles im Internet lesen!Wie man eine Rentenversicherung bewertetMehr über den Geldlehrer e.V. erfahrenPräsentiert von BlinkistDiese Folge wird Dir präsentiert von Blinkist, der App für Menschen, die mehr wissen möchten. Blinkist ist eine App, mit der du dir die Kernaussagen aus über 2.500 Büchern in nur 15 Minuten durchlesen oder anhören kannst.Thematisch werden dort alle Themen rund um den Finanzrocker-Podcast abgedeckt wie Finanzen, Persönliche Entwicklung. Im Moment gibt es eine Aktion exklusiv für Hörer meines Podcast erhältst Du 25% Rabatt auf das Jahresabo Blinkist Premium. Es gibt ein Probeabo mit dem ihr kostenlos alles testen und euch in Ruhe anschauen könnt.Hol‘ Dir 25 % Rabatt auf das Premium-Jahresabo hier."
}, {
    "title": "Folge 104: Regelmäßiges Einkommen mit Hochdividendenwerten - Interview mit Luis Pazos",
    "itunes_title": "Folge 104: Regelmäßiges Einkommen mit Hochdividendenwerten - Interview mit Luis Pazos",
    "episode": "104",
    "date": "Wed, 19 Sep 2018 05:16:42 +0000",
    "link": "https://finanzrocker.podigee.io/104-folge-104-regelmassiges-einkommen-mit-hochdividendenwerten-interview-mit-luis-pazos",
    "author": "Daniel Korth - Finanz-Blogger, Podcaster und Co-Host von \"Der Finanzwesir rockt\"",
    "description": "Regelmäßiges Einkommen mit Hochdividendenwerten ist ein Thema, das ich bisher nur am Rande im Podcast besprochen habe. Dabei setzen vor allem in den USA und Kanada sehr viele Renter auf diese Einkommensströme. Mit Luis Pazos habe ich den passenden Experten im Interview, der seit vielen Jahren in diese Werte investiert.Luis habe ich auf der INVEST in Stuttgart persönlich kennengelernt. Dort hat er mir auch sein Buch mitgegeben. Seitdem haben wir uns gleich zweimal getroffen und ich habe ihn so etwas besser kennengelernt. Ich schätze die Ansichten von Luis und bin beeindruckt von seinem Wissen.Hör Dir die 90 Minuten doch mal an und entscheide selbst, ob Hochdividendenwerte auch etwas für Dich sind. Auch das Buch von Luis kann ich wirklich empfehlen. Eine Zusammenfassung des Interviews findest Du im Blog.Präsentiert von BlinkistDiese Folge wird Dir präsentiert von Blinkist, der App für Menschen, die mehr wissen möchten. Blinkist ist eine App, mit der du dir die Kernaussagen aus über 2.500 Büchern in nur 15 Minuten durchlesen oder anhören kannst.Thematisch werden dort alle Themen rund um den Finanzrocker-Podcast abgedeckt wie Finanzen, Persönliche Entwicklung. Im Moment gibt es eine Aktion exklusiv für Hörer meines Podcast erhältst Du 25% Rabatt auf das Jahresabo Blinkist Premium. Es gibt ein Probeabo mit dem ihr kostenlos alles testen und euch in Ruhe anschauen könnt.Hol‘ Dir 25 % Rabatt auf das Premium-Jahresabo hier.ShownotesZu den Blogbeiträgen auf Nur Bares ist Wahres!Zum Buch \"Bargeld statt Buchgewinn\"*Zum Buch \"Geldanlage in REITs\"Gratiskurs zum Thema HochdividendenwerteAlle Leistungen im ÜberblickWertpapierverwahrung und WertpapierleiheBesteuerung von (Hoch-)DividendenwertenZur Facebook-Gruppe Einkommensinvestoren ",
    "summary": "Regelmäßiges Einkommen mit Hochdividendenwerten ist ein Thema, das ich bisher nur am Rande im Podcast besprochen habe. Dabei setzen vor allem in den USA und Kanada sehr viele Renter auf diese Einkommensströme. Mit Luis Pazos habe ich den passenden Experten im Interview, der seit vielen Jahren in diese Werte investiert.Luis habe ich auf der INVEST in Stuttgart persönlich kennengelernt. Dort hat er mir auch sein Buch mitgegeben. Seitdem haben wir uns gleich zweimal getroffen und ich habe ihn so etwas besser kennengelernt. Ich schätze die Ansichten von Luis und bin beeindruckt von seinem Wissen.Hör Dir die 90 Minuten doch mal an und entscheide selbst, ob Hochdividendenwerte auch etwas für Dich sind. Auch das Buch von Luis kann ich wirklich empfehlen. Eine Zusammenfassung des Interviews findest Du im Blog.Präsentiert von BlinkistDiese Folge wird Dir präsentiert von Blinkist, der App für Menschen, die mehr wissen möchten. Blinkist ist eine App, mit der du dir die Kernaussagen aus über 2.500 Büchern in nur 15 Minuten durchlesen oder anhören kannst.Thematisch werden dort alle Themen rund um den Finanzrocker-Podcast abgedeckt wie Finanzen, Persönliche Entwicklung. Im Moment gibt es eine Aktion exklusiv für Hörer meines Podcast erhältst Du 25% Rabatt auf das Jahresabo Blinkist Premium. Es gibt ein Probeabo mit dem ihr kostenlos alles testen und euch in Ruhe anschauen könnt.Hol‘ Dir 25 % Rabatt auf das Premium-Jahresabo hier.ShownotesZu den Blogbeiträgen auf Nur Bares ist Wahres!Zum Buch \"Bargeld statt Buchgewinn\"*Zum Buch \"Geldanlage in REITs\"Gratiskurs zum Thema HochdividendenwerteAlle Leistungen im ÜberblickWertpapierverwahrung und WertpapierleiheBesteuerung von (Hoch-)DividendenwertenZur Facebook-Gruppe Einkommensinvestoren "
}, {
    "title": "Folge 102: \"Dienstleister müssen auch Geld verdienen!\" - Interview mit Tobias Kramer von echtgeld.tv",
    "itunes_title": "Folge 102: \"Dienstleister müssen auch Geld verdienen!\" - Interview mit Tobias Kramer von echtgeld.tv",
    "episode": "102",
    "date": "Wed, 05 Sep 2018 04:39:37 +0000",
    "link": "https://finanzrocker.podigee.io/102-folge-102-dienstleister-mussen-auch-geld-verdienen-interview-mit-tobias-kramer-von-echtgeld-tv",
    "author": "Daniel Korth - Finanz-Blogger, Podcaster und Co-Host von \"Der Finanzwesir rockt\"",
    "description": "Die Sommerpause im Finanzrocker-Podcast hat ein Ende und mit Tobias Kramer von echtgeld.tv habe ich einen wirklich interessanten Gesprächspartner zu Gast. Wir sprechen über Finanzbildung bei YouTube, Zertifikate als Investitionsvehikel, Länder-ETFs als Beimischung und warum Dienstleister auch Geld verdienen müssen.Tobias habe ich auf der INVEST in Stuttgart persönlich kennengelernt. Da Echtgeld.tv meine Lieblingssendung bei YouTube ist, sprach ich ihn gleich an. Dort tauschten wir uns in der Blogger-Lounge das erste Mal aus. Kurze Zeit später war ich zu Gast bei echtgeld.tv (siehe unten) und wir sprachen auch über ein Interview im Finanzrocker-Podcast. Mit 100 Minuten ist es mal wieder etwas länger geworden, aber es lohnt sich.Shownotes Interview mit Tobias Kramer von echtgeld.tvZu Echtgeld.tvZu Adorum PublishingZum ZertifikateberaterTobias Account bei KivaZum Interview mit Christian W. Röhl von DividendenadelZur Buchbesprechung von \"Cool bleiben und Dividenden kassieren\"Präsentiert von BlinkistDiese Folge wird Dir präsentiert von Blinkist, der App für Menschen, die mehr wissen möchten. Blinkist ist eine App, mit der du dir die Kernaussagen aus über 2.500 Büchern in nur 15 Minuten durchlesen oder anhören kannst.Thematisch werden dort alle Themen rund um den Finanzrocker-Podcast abgedeckt wie Finanzen, Persönliche Entwicklung. Im Moment gibt es eine Aktion exklusiv für Hörer meines Podcast erhältst Du 25% Rabatt auf das Jahresabo Blinkist Premium. Es gibt ein Probeabo mit dem ihr kostenlos alles testen und euch in Ruhe anschauen könnt.Hol‘ Dir 25 % Rabatt auf das Premium-Jahresabo hier.Shownotes Interview mit Tobias Kramer von echtgeld.tvZu Echtgeld.tvZu Adorum PublishingZum ZertifikateberaterTobias Account bei KivaZum Interview mit Christian W. Röhl von DividendenadelZur Buchbesprechung von \"Cool bleiben und Dividenden kassieren\"Zur ausführlichen Zusammenfassung im Blog geht es hier.",
    "summary": "Die Sommerpause im Finanzrocker-Podcast hat ein Ende und mit Tobias Kramer von echtgeld.tv habe ich einen wirklich interessanten Gesprächspartner zu Gast. Wir sprechen über Finanzbildung bei YouTube, Zertifikate als Investitionsvehikel, Länder-ETFs als Beimischung und warum Dienstleister auch Geld verdienen müssen.Tobias habe ich auf der INVEST in Stuttgart persönlich kennengelernt. Da Echtgeld.tv meine Lieblingssendung bei YouTube ist, sprach ich ihn gleich an. Dort tauschten wir uns in der Blogger-Lounge das erste Mal aus. Kurze Zeit später war ich zu Gast bei echtgeld.tv (siehe unten) und wir sprachen auch über ein Interview im Finanzrocker-Podcast. Mit 100 Minuten ist es mal wieder etwas länger geworden, aber es lohnt sich.Shownotes Interview mit Tobias Kramer von echtgeld.tvZu Echtgeld.tvZu Adorum PublishingZum ZertifikateberaterTobias Account bei KivaZum Interview mit Christian W. Röhl von DividendenadelZur Buchbesprechung von \"Cool bleiben und Dividenden kassieren\"Präsentiert von BlinkistDiese Folge wird Dir präsentiert von Blinkist, der App für Menschen, die mehr wissen möchten. Blinkist ist eine App, mit der du dir die Kernaussagen aus über 2.500 Büchern in nur 15 Minuten durchlesen oder anhören kannst.Thematisch werden dort alle Themen rund um den Finanzrocker-Podcast abgedeckt wie Finanzen, Persönliche Entwicklung. Im Moment gibt es eine Aktion exklusiv für Hörer meines Podcast erhältst Du 25% Rabatt auf das Jahresabo Blinkist Premium. Es gibt ein Probeabo mit dem ihr kostenlos alles testen und euch in Ruhe anschauen könnt.Hol‘ Dir 25 % Rabatt auf das Premium-Jahresabo hier.Shownotes Interview mit Tobias Kramer von echtgeld.tvZu Echtgeld.tvZu Adorum PublishingZum ZertifikateberaterTobias Account bei KivaZum Interview mit Christian W. Röhl von DividendenadelZur Buchbesprechung von \"Cool bleiben und Dividenden kassieren\"Zur ausführlichen Zusammenfassung im Blog geht es hier."
}]
    form = PodcastSearchForm()
    if form.validate_on_submit():
        return redirect(url_for('search', podcast=form.podcast.data))
    user = {'username':'Philipp'}
    return render_template('index.html', title='Podcastdeck', user=user, podcasts=podcasts, form=form)